# Generated by Django 2.0.2 on 2018-04-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='icom',
            new_name='icon',
        ),
    ]
